################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2


################ Spanish language ##################
[en]
languageName = "Espa√±ol"
languageCode = "es"
contentDir = "content/spanish"
weight = 1
